fun main(){
    print("Enter Enroll no: ")
    val enrollno = readLine()
    print("Enter Name: ")
    val name= readLine()
    print("Enter Age: ")
    val age= readLine()
    print("Enter Class: ")
    val classname= readLine()
    print("Enter Branch: ")
    val branch= readLine()
    print("Enter College: ")
    val college= readLine()
    print("Enter University: ")
    val university= readLine()
    println("\n********************")
    println("Student's Data:")
    println("Enrollment No.: $enrollno")
    println("Name: $name")
    println("Age: $age")
    println("Branch: $branch")
    println("Class: $classname")
    println("Batch: $branch")
    println("College Name: $college")
    println("University Name: $university")}